### Lambda

In [3]:
def sum1(a,b):
    c = a + b
    return c
sum1(8,6)

14

In [4]:
a = lambda x,y: x + y
a(8,6)

14

### List comprehension

In [1]:
a = int(input())
for i in range(0,a+1):
    print(i**2)

5
0
1
4
9
16
25


In [3]:
a = [i**2 for i in range(1,11)]
a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [1]:
a = int(input())
b = 1
for i in range(1,a+1):
    b *= i 
print(b)

5
120


In [3]:
import math
s =[math.factorial(i) for i in range(1,10)]
s

[1, 2, 6, 24, 120, 720, 5040, 40320, 362880]

In [4]:
n = int(input())
m = 10
l = [n*i for i in range(1,m+1)]
l

123


[123, 246, 369, 492, 615, 738, 861, 984, 1107, 1230]

### File Handling

* performing`operations on a file is called file Handling
* entering some data to a file is called as write to a file
* Retriving data from a file is called as reading  from a file
* we can perform append, delete operations on file

In [7]:
def writetoafile(filename,data):
    with open(filename,"w") as f:
        f.write(data)
        return
    filename = "data.txt"
    writetoafile(filename,"line1\nline2\n")

In [25]:

def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
        f.close()
        return fd
    filename = "data.txt"
    readfromafile("data.txt")
    def printlines(filename):
        with open(filename,"r") as f:
            for line in f:
                print(line,end = " ")
                return
            printlines(filename)
            print(readfromafile(filename))

In [1]:
def appendtofile(filename,data):
    with open(filename,"a") as f:
        for line in data:
            f.write("\n"+line)
            return
        data = ["line3","line4","line5","line6"]
        filename = "data.txt"
        appendtofile(filename,data)

### numpy

* numpy is an advanced library.
* numpy---numarical python
* numpy is two perfoam mathmatical and stastical operations
* the values are represented in the form of rows and coloumns
* advantages of numpy when compared to lists 
 * it takes less time 
 * performens will be highy 
  * occupies to less memory

In [25]:
import numpy as np

In [26]:
### creating an array using numpy
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [27]:
### creating an array in particular range
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
### checking the number of elements 
a.size

10

In [29]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
a - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [31]:
a2 = np.array([[1,2,3,4],[5,6,7,8]],dtype = complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [32]:
a2.dtype

dtype('complex128')

In [33]:
np.arange

<function numpy.arange>

In [34]:
a.dtype

dtype('int32')

In [36]:
### comprasion of two arrays 

a = np.array([[1,2,3,4],[4,5,6,7]])
b = np.array([[4,5,6,7],[3,4,5,6]])
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [37]:
a < b

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [38]:
a > b

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [39]:
a * b

array([[ 4, 10, 18, 28],
       [12, 20, 30, 42]])

In [40]:
a // b

array([[0, 0, 0, 0],
       [1, 1, 1, 1]], dtype=int32)

In [41]:
a - b

array([[-3, -3, -3, -3],
       [ 1,  1,  1,  1]])

In [43]:
a % b

array([[1, 2, 3, 4],
       [1, 1, 1, 1]], dtype=int32)

In [44]:
a ++ b

array([[ 5,  7,  9, 11],
       [ 7,  9, 11, 13]])

In [45]:
a == b 

array([[False, False, False, False],
       [False, False, False, False]])

In [47]:
a << b

array([[ 16,  64, 192, 512],
       [ 32,  80, 192, 448]], dtype=int32)

In [49]:
np.var(b)

1.5

In [51]:
b


array([[4, 5, 6, 7],
       [3, 4, 5, 6]])

In [52]:
np.argmax(b)

3

In [53]:
np.transpose(b)

array([[4, 3],
       [5, 4],
       [6, 5],
       [7, 6]])

In [60]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])